name: weatherapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  http: ^1.1.0
  intl: ^0.18.1
  sleek_circular_slider: ^2.0.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  

flutter:
  uses-material-design: true
  assets:
  - assets/icons/
